# Generated by Django 4.2.7 on 2024-09-25 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="post",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="post",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="post",
            name="food_weight",
        ),
        migrations.AddField(
            model_name="post",
            name="grams",
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="food_photos/"),
        ),
        migrations.CreateModel(
            name="UserNutritionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_calories", models.FloatField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
