# Generated by Django 4.2.7 on 2024-09-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_content_comment_text_remove_post_calories_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserNutritionGoal",
        ),
    ]
