# Generated by Django 5.1.1 on 2024-09-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0008_remove_foodupload_image_url_foodupload_image"),
        ("posts", "0004_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="grams",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="food_upload",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="health.foodupload",
            ),
            preserve_default=False,
        ),
    ]
