# Generated by Django 5.1.1 on 2024-09-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_post_grams_remove_post_image_post_food_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="food_upload",
        ),
        migrations.AddField(
            model_name="post",
            name="grams",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="food_photos/"),
            preserve_default=False,
        ),
    ]
