# Generated by Django 5.1.1 on 2024-09-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0009_foodupload_last_meal"),
        ("posts", "0006_remove_post_food_upload_post_grams_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="food_uploads",
            field=models.ManyToManyField(to="health.foodupload"),
        ),
        migrations.AddField(
            model_name="post",
            name="goal_calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="goal_carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="goal_fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="goal_protein",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="result",
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="total_calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="total_carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="total_fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="total_protein",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
