# Generated by Django 5.1.1 on 2024-09-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_remove_post_grams_remove_post_image_post_caption_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="grams",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
