# Generated by Django 5.1.1 on 2024-09-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0005_dailynutrition"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodupload",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodupload",
            name="carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodupload",
            name="fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodupload",
            name="protein",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
