# Generated by Django 5.1.1 on 2024-09-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_foodupload_calories_foodupload_carbs_foodupload_fat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodupload",
            name="image",
        ),
        migrations.AddField(
            model_name="foodupload",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
