# Generated by Django 5.1.1 on 2024-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0007_remove_foodupload_image_foodupload_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodupload",
            name="image_url",
        ),
        migrations.AddField(
            model_name="foodupload",
            name="image",
            field=models.ImageField(default=1, upload_to="food_images/"),
            preserve_default=False,
        ),
    ]
