# Generated by Django 5.1.1 on 2024-09-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0008_remove_foodupload_image_url_foodupload_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodupload",
            name="last_meal",
            field=models.BooleanField(default=False),
        ),
    ]
